name: Release new version

on:
  workflow_dispatch:
    inputs:
      pythonVersion:
        description: "Python Version"
        required: true
        type: string
      baseImage:
        description: "Base Image"
        type: string
        required: true
      short_version_tag:
        description: "Add short version tag"
        type: choice
        required: true
        default: 'true'
        options:
          - 'true'
          - 'false'

run-name: Build Python ${{ inputs.pythonVersion }} on ${{ inputs.baseImage }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Setup env variables
        run: bash build-helper.sh ${pythonVersion} ${baseImage} ${shortVersionTag}
        env:
          pythonVersion: ${{ inputs.pythonVersion }}
          baseImage: ${{ inputs.baseImage }}
          shortVersionTag: ${{ inputs.short_version_tag }}

      - name: Check env variables
        run: |
          echo "DOCKER_TAG=${{ env.DOCKER_TAG }}"
          echo "BASE_IMAGE=${{ env.BASE_IMAGE }}"
          echo "PY_VERSION=${{ env.PY_VERSION }}"

      - name: Check docker file
        run: |
          cat Dockerfile
          pwd
          ls -la

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build_1
        uses: docker/build-push-action@v5
        if: ${{ inputs.short_version_tag }}== 'true'
        with:
          push: true
          tags: "brikerman/python:${{ env.DOCKER_SHORT_TAG }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max'
          context: "/home/runner/work/python-docker-builder/python-docker-builder"
          platforms: linux/amd64,linux/arm64/v8

      - name: Build and push
        id: docker_build_2
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: "brikerman/python:${{ env.DOCKER_FULL_TAG }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max'
          context: "/home/runner/work/python-docker-builder/python-docker-builder"
          platforms: linux/amd64,linux/arm64/v8

      - name: Print image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
